import { Product } from './product.model';

export const initialProducts: Product[] = [
  { id: 'pizza-classic-pepperoni', name: 'Classic Pepperoni', category: 'Pizza', description: 'Mozzarella cheese and savory pepperoni on a freshly baked crust.', price: 299, mediumPrice: 299, largePrice: 449 },
  { id: 'pizza-hawaiian', name: 'Hawaiian', category: 'Pizza', description: 'A sweet and savory combination of ham, pineapple, and mozzarella cheese.', price: 329, mediumPrice: 329, largePrice: 479 },
  { id: 'pizza-margherita', name: 'Margherita', category: 'Pizza', description: 'Tomato sauce, mozzarella cheese, and fresh basil.', price: 279, mediumPrice: 279, largePrice: 419 },
  { id: 'pizza-cheesy-bacon', name: 'Cheesy Bacon', category: 'Pizza', description: 'Crispy bacon, mozzarella, and extra cheese for a rich and savory flavor.', price: 349, mediumPrice: 349, largePrice: 499 },
  { id: 'pizza-supreme', name: 'Supreme', category: 'Pizza', description: 'Pepperoni, ham, mushrooms, bell peppers, onions, and mozzarella cheese.', price: 399, mediumPrice: 399, largePrice: 569 },
  { id: 'pizza-bbq-chicken', name: 'BBQ Chicken', category: 'Pizza', description: 'Grilled chicken, BBQ sauce, onions, and melted mozzarella cheese.', price: 359, mediumPrice: 359, largePrice: 519 },
  { id: 'pizza-four-cheese', name: 'Four Cheese', category: 'Pizza', description: 'A delicious blend of four different cheeses on a golden crust.', price: 379, mediumPrice: 379, largePrice: 539 },
  { id: 'pizza-all-meat', name: 'All Meat', category: 'Pizza', description: 'Loaded with pepperoni, ham, bacon, sausage, and mozzarella cheese.', price: 399, mediumPrice: 399, largePrice: 569 },
  { id: 'pizza-honey-glazed-spinach', name: 'Honey Glazed Spinach', category: 'Pizza', description: 'A perfect balance of savory and sweet featuring creamy spinach, melted mozzarella, and a drizzle of rich honey.', price: 389, mediumPrice: 389, largePrice: 549 },
  { id: 'pizza-creamy-spinach', name: 'Creamy Spinach', category: 'Pizza', description: 'A rich and savory blend of fresh spinach, cream cheese, garlic, and melted mozzarella on a golden crust.', price: 379, mediumPrice: 379, largePrice: 539 },
  { id: 'side-garlic-bread', name: 'Garlic Bread', category: 'Sides', description: 'Toasted bread topped with garlic butter and herbs.', price: 129 },
  { id: 'side-mozzarella-sticks', name: 'Mozzarella Sticks', category: 'Sides', description: 'Crispy breaded mozzarella sticks served with dipping sauce.', price: 179 },
  { id: 'side-chicken-wings', name: 'Chicken Wings', category: 'Sides', description: 'Juicy chicken wings coated in your choice of flavorful sauce.', price: 229 },
  { id: 'side-potato-wedges', name: 'Potato Wedges', category: 'Sides', description: 'Crispy seasoned potato wedges perfect for sharing.', price: 149 },
  { id: 'side-cheesy-fries', name: 'Cheesy Fries', category: 'Sides', description: 'Crispy fries topped with creamy melted cheese.', price: 169 },
  { id: 'side-onion-rings', name: 'Onion Rings', category: 'Sides', description: 'Crispy golden battered onion rings served with dip.', price: 159 },
  { id: 'side-nachos-supreme', name: 'Nachos Supreme', category: 'Sides', description: 'Tortilla chips loaded with cheese, salsa, and jalapeños.', price: 199 },
  { id: 'side-buffalo-cauliflower', name: 'Buffalo Cauliflower', category: 'Sides', description: 'Crispy cauliflower bites tossed in spicy buffalo sauce.', price: 179 },
  { id: 'side-calamari-rings', name: 'Calamari Rings', category: 'Sides', description: 'Golden fried squid rings served with tangy dip.', price: 219 },
  { id: 'side-loaded-potato-skins', name: 'Loaded Potato Skins', category: 'Sides', description: 'Baked potato skins topped with cheese, bacon bits, and sour cream.', price: 189 },
  { id: 'drink-coca-cola', name: 'Coca-Cola', category: 'Drinks', description: 'Chilled classic cola drink.', price: 79 },
  { id: 'drink-sprite', name: 'Sprite', category: 'Drinks', description: 'Refreshing lemon-lime soft drink.', price: 79 },
  { id: 'drink-iced-tea', name: 'Iced Tea', category: 'Drinks', description: 'Cool and refreshing sweetened iced tea.', price: 89 },
  { id: 'drink-lemonade', name: 'Lemonade', category: 'Drinks', description: 'Refreshing lemonade with a sweet and tangy flavor.', price: 99 },
  { id: 'drink-bottled-water', name: 'Bottled Water', category: 'Drinks', description: 'Chilled purified drinking water.', price: 59 },
  { id: 'drink-root-beer', name: 'Root Beer', category: 'Drinks', description: 'Rich and creamy classic root beer.', price: 79 },
  { id: 'drink-fresh-orange-juice', name: 'Fresh Orange Juice', category: 'Drinks', description: 'Freshly squeezed orange juice, cold and tangy.', price: 109 },
  { id: 'drink-iced-coffee', name: 'Iced Coffee', category: 'Drinks', description: 'Smooth chilled coffee served over ice.', price: 119 },
  { id: 'drink-mango-shake', name: 'Mango Shake', category: 'Drinks', description: 'Thick and creamy mango fruit shake.', price: 129 },
  { id: 'drink-sparkling-water', name: 'Sparkling Water', category: 'Drinks', description: 'Chilled sparkling mineral water.', price: 69 },
];
